title: Bespoke Synth User Docs
description: Community-built documentation for bespoke synth.
baseurl: "/BespokeSynthDocs"
url: "https://bespokesynth.github.io"
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
aux_links:
  "bespokesynth.com":
    - "https://www.bespokesynth.com/"
  "github.com":
    - "https://github.com/BespokeSynth/BespokeSynth"
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - backup/
